# Generated by Django 5.2.4 on 2025-07-18 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='semester',
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('Subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subjects')),
            ],
        ),
    ]
